### ISSUE TITLE
无法启动项目

### ISSUE THREAD

**Issue by alazeprt** [Yuns-Lab/YunSchedule#4]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Yuns-Lab/YunSchedule/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在手机termux中使用ubuntu的wine启动项目releases中的exe文件时，无法启动

### 重现步骤（如果有）

执行wine xxx.exe命令

### 截图（必须） / 日志（如有）

![image](https://github.com/Yuns-Lab/YunSchedule/assets/92018941/6ff7c3ef-ef0d-41ea-b8e3-f61f89dd2012)

### 意向调查

- [ ] 我愿意为此反馈做出贡献

**Comment by lingyunawa** [comment]
不打算支持 Linux，这是图形化应用...
